name: letsbeenextgenrider
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.10.0
  get: ^3.17.1
  get_storage: ^1.3.2
  http: ^0.12.2
  flutter_svg: ^0.19.1
  permission_handler: ^5.0.1+1
  geocoder: ^0.2.1
  location: ^3.2.4
  flutter_local_notifications: ^3.0.3
  socket_io_client: ^0.9.11
  auto_size_text: ^2.1.0
  google_maps_flutter: ^1.0.6
  badges: ^1.1.6
  url_launcher: ^5.7.10
  data_connection_checker: ^0.3.4
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: CooperBlack
      fonts:
        - asset: fonts/COOPBL.TTF
