name: letsbeenextgenrider
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.10.0

  # Dependency Injection
  get: ^3.17.1

  # Shared preference
  get_storage: ^1.3.2

  # Http request
  http: ^0.12.2

  # Svg 
  flutter_svg: ^0.19.1
  
  # Permission
  permission_handler: ^5.0.1+1

  # Locations
  geocoder: ^0.2.1
  location: ^3.2.4

  # Notification builder
  flutter_local_notifications: ^3.0.3

  # Socket IO
  socket_io_client: ^0.9.11

  # Auto text resize
  auto_size_text: ^2.1.0

  #Google Maps
  google_maps_flutter: ^1.0.6

  #Badge
  badges: ^1.1.6

  #Phone call
  flutter_phone_direct_caller: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/png/
